### PR TITLE
PullRequest for Issue1912: add context menu for the combox of scaler channel view

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
#1912 
- add context menu to the value combox of scaler channel view
- refactor the codes

### CODE REVIEW

**Comment by XuetaoLiu-CLS** [comment]
@helfrij can you take a look at this PR? I tried to use the context menu the same way as you did.

**Comment by helfrij** [comment]
Looks good, @XuetaoLiu-CLS!

Time Estimate: 10 minutes.

**Comment by dretrex** [comment]
Overall, this looks good to me too.  One quick question I had @XuetaoLiu-CLS is, does this refactor alleviate the problem of right clicking on the combo box not generating the pop up?
Time Estimate: 3 minutes

**Comment by XuetaoLiu-CLS** [comment]
@dretrex yes, it fixed the issue with the following changes:
https://github.com/acquaman/acquaman/blob/Issue1912/source/ui/beamline/AMCurrentAmplifierView.cpp#L74

**Comment by dretrex** [comment]
Great.  I'll merge this in then.

**Pull request merged**
