### PR TITLE
Pull Request for Issue1996: Removing clockSource_

### PR DESCRIPTION
**Pull request by helfrij**
Removed the clockSource_ control from BioXASSIS3820Scaler, as it didn't end up being a component of moving the scaler from software triggered to hardware triggered (Zebra). Removed it's editor view from BioXASSIS3820ScalerView.

### CODE REVIEW

**Comment by dretrex** [comment]
Were you wanting someone to review this @helfrij?

**Comment by helfrij** [comment]
Hey @XuetaoLiu-CLS, would you take a look at this pull request?

**Comment by XuetaoLiu-CLS** [comment]
Looks good.

Time Estimate: 2 minutes

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 1 minute

**Pull request merged**
