### PR TITLE
Pull Request Issue2072: 'Components' tab collapsed by default on Side

### PR DESCRIPTION
**Pull request by helfrij**
- Added two new slots to AMMainWindow, one for collapsing a sidebar item by QModelIndex, and another for collapsing a sidebar item by name.
- Added call to collapsing method to BioXAS Side app controller.

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @iainworkman, would you take a look at this pull request?

**Comment by iainworkman** [comment]
Looks good to me.
Time Estimate: 1 Minute.

**Comment by helfrij** [comment]
@dretrex merge conflicts fixed here too.

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 1 minute

**Pull request merged**
