### PR TITLE
Revert "Pull request for Issue942: Make a convenience static getter for ...

### PR DESCRIPTION
**Pull request by dleacock**
Reverts acquaman/acquaman#1138

I'm trying to add my newest commits to the pull request. Hopefully I didn't screw things up.

### CODE REVIEW

**Comment by dleacock** [comment]
https://github.com/acquaman/acquaman/commit/89d21a010765cc26748b30ea5ceb0425abf87cd3

**Comment by dleacock** [comment]
Added AMActionSupport to REIXS

https://github.com/acquaman/acquaman/commit/2c14cb0fb87d279003312d001f9354eee4cbe399

**Comment by dleacock** [comment]
Added AMSupportAction to SGMMAXvMotor and SGMBeamline

https://github.com/acquaman/acquaman/commit/d84fe9c17308eafb936f5b8073082deca7bced76

**Comment by dleacock** [comment]
Added AMActionSupport to SGMFastActionController

https://github.com/acquaman/acquaman/commit/54d4df127f7ae2c0e251845cf5c4f2f262319a6d

**Comment by davidChevrier** [comment]
No longer applicable.

**Pull request closed without merging**
