### PR TITLE
Pull Request for Issue1408: BioXAS XAS scan estimated time display incorrect

### PR DESCRIPTION
**Pull request by dleacock**
BioXASSide and BioXASMain were missing connections and setters that allowed the ConfigView to be updated by change in estimated time in the Configuration.  

Estimated: 2

### CODE REVIEW

**Comment by dleacock** [comment]
This can be removed.  Was done in 1408a

**Comment by dretrex** [comment]
What can be removed?  Also, you didn't include enough of the hash for the markdown to generate a link.

**Comment by dleacock** [comment]
This pull request can be removed. It's already in 1408a

**Comment by dretrex** [comment]
Okay.  Just as an FYI, you usually need at least six characters of the hash code for the commit to show up as a hyperlink.

**Pull request closed without merging**
