### PR TITLE
PullRequest for Issue1210: Display the estimated time and total scan points

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
https://github.com/acquaman/acquaman/issues/1210

@dretrex @davidChevrier @epengr

### CODE REVIEW

**Comment by dretrex** [comment]
Whoa whoa.  How is it that there is still a UI form?  I thought you removed all of these @iainworkman?

**Comment by XuetaoLiu-CLS** [comment]
@dretrex @iainworkman I was surprised as well. I was thinking removing the ui file in this PR. But after a second thought, I think it will be better in another thread.

**Comment by XuetaoLiu-CLS** [comment]
actually, there are more ui files in REIXS acquaman.

**Comment by dretrex** [comment]
Okay, if you are going to do that then I'll merge this in so you can branch off with the change already intact so you don't have to worry about redoing the change.

**Comment by epengr** [comment]
I'm a little confused about why that ever was a UI form... - I thought that view was new with the new scan controller?  Or did we actually just slot your new regions view into the old scanConfigurationView @dretrex?

And was it seriously just not updating the labels?  I did work at one point, I swear...  How'd that go away?

**Comment by dretrex** [comment]
Probably the latter.  Who knows.  The important thing is that it'll be fixed and we'll never have to worry about it again.

**Comment by epengr** [comment]
... Ever? 

Very glad for the help.

**Comment by iainworkman** [comment]
Absolutely no idea how those got missed. I did a search for classes with *.ui in the locate box at the bottom, and also searched in the file system.

**Pull request merged**
