### PR TITLE
Pull Request for Issue2004: BioXASImagingBeamline to inherit from BioXASBeamline

### PR DESCRIPTION
**Pull request by helfrij**
Modified BioXASImagingBeamline to inherit from BioXASBeamline.

### CODE REVIEW

**Comment by dretrex** [comment]
Did you want a reviewer for this one too?

**Comment by helfrij** [comment]
Hey @iainworkman, would you take a look at this pull request?

**Comment by iainworkman** [comment]
Looks good to me. Time Estimate 5 minutes.

**Comment by dretrex** [comment]
Looks good to me.
Time Estimate: 1 minute

**Pull request merged**
