### PR TITLE
Pull Request for Issue1961: Removing BioXAS shutter tool

### PR DESCRIPTION
**Pull request by helfrij**
- Deleted files.
- Removed references to files/classes from BioXASToolSuite

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @XuetaoLiu-CLS, would you take a look at this pull request?

**Comment by XuetaoLiu-CLS** [comment]
Looks good. More codes removed :clap: 

Time Estimate: 2 minutes

**Comment by helfrij** [comment]
Thanks, @XuetaoLiu-CLS! Finished the clean build, there were no problems.

**Comment by dretrex** [comment]
Time Estimate: 3 minutes

**Pull request merged**
