### PR TITLE
Pull Request for Issue2036: Fixing valves moving state

### PR DESCRIPTION
**Pull request by helfrij**
First stab:
I've reimplemented updateMoving() in BioXASValves so that the valves never report as moving. The valves are currently reporting as moving erroneously because there are valves closed on Imaging while the Kohzu is vented.

Death blow:
Reversed first stab and just commented out the offending valves.

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @iainworkman, would you take a look?

**Comment by dretrex** [comment]
Won't this affect actions that open and close the valves?

**Comment by helfrij** [comment]
I don't think so. The state that's associated specifically with move actions is the 'move in progress' state, different than the 'is moving' state. This change should just impact the display aspect of moving. This is definitely something I can double-check on Monday though.

**Comment by iainworkman** [comment]
The code looks fine. There is still the question as to whether the is moving state always being false impacts on the general behaviour, but this will be resolved with testing.
Time Estimate: 2 minutes

**Comment by helfrij** [comment]
Tested this today by opening the valves in Acquaman when some valves on the beamline where closed. All valves that are able to be opened are, but the ones that can't be opened (the ones that are closed while the Imaging mono is vented) fail. The valves value displays as 'Unknown' and the valve status button is red. The moving status aspect of this problem is solved.

However, the valves and beam status still report as 'Unknown' or 'Off'. A better solution for now may actually be to comment out adding those valves to the beam status. This way, the beam status can report as On and the valves as okay.

**Comment by helfrij** [comment]
Made the change commenting out the valves.

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 1 minute

**Pull request merged**
