### PR TITLE
Pull Request for Issue 1774: Various SGM Deploy Issues

### PR DESCRIPTION
**Pull request by iainworkman**
- Added back the undulator
- Added a sample chamber lights slider/control
- Stopped the coordinator trying to reset the undulator velocity (the encoder handles this itself)
- Made the AMConnectedControl::updateConnected() slot virtual (I needed this because I use this in some of my controls, if this is going to cause an issue in your code which uses these @helfrij let me know)

### CODE REVIEW

**Comment by helfrij** [comment]
Shouldn't be a problem @iainworkman!

**Comment by dretrex** [comment]
Overall, looks good.  However, you may want to look into your whitespace settings since there are a bunch of lines of code that are offset by a single space.
Time Estimate: 5 minutes

**Comment by iainworkman** [comment]
Those white spacing issues came down to having to do a bunch of rushed work under the sgm-upgrade account, which I assume doesn't have the white-space things set up correctly.

**Comment by dretrex** [comment]
Okay, can you make sure they are setup correctly for the future so we can minimize those kinds of changes?

**Pull request merged**
