### PR TITLE
PullRequest for Issue2412 refine the logic to initialize the data folder

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
refine the logic to create/initialize the data storage
#2412

### CODE REVIEW

**Comment by XuetaoLiu-CLS** [comment]
Testing:
- [ ]  new proposal number: 
    - [ ] both local / remote folder created successfully; 
    - [ ] second launch work as expected

- [ ]  existing proposal number: 
    - delete local folder; 
       - [ ] launch up, we should synch remote to local 
       - [ ] second launch work as expected
    - delete remote  folder; 
       - [ ] launch up, the history scan data should be loaded; when closing, we should synch to remote
       - [ ] second launch work as expected

- [ ]  scan testing
       - [ ] scan data and exported data are saved properly

**Comment by XuetaoLiu-CLS** [comment]
@mButlerDM this is my latest changes. It refactored what you did before, please have a look to see whether it solved your original issue or not. 
(you can also modify my comments on testing to add more test cases you preferred.)

**Comment by mButlerDM** [comment]
@XuetaoLiu-CLS added my two test cases and pulled your branch to test, original issue is okay in the refactor

**Comment by helfrij** [comment]
Looks good, @XuetaoLiu-CLS.

Time Estimate: 5 minutes.

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 5 minutes

**Pull request merged**
