### PR TITLE
PullRequest for Issue1822: Initialize the state of the SR570 sens_put control when it is connect

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
Initialize the state of the SR570 sens_put control when it is connected on the first time
#1822

### CODE REVIEW

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 1 minute

**Comment by iainworkman** [comment]
I'm going to briefly restore this branch, so I can get it into deploy as a hotfix right away. I'll delete it again afterwards.

**Comment by dretrex** [comment]
Sounds good.

**Comment by iainworkman** [comment]
@XuetaoLiu-CLS Will this require the SR570 coordinator application to also be redeployed?

**Comment by XuetaoLiu-CLS** [comment]
@iainworkman yes, since SR570 is also using the same class. That's also why we have to restart both IOC app and SR570 coordinator app

**Comment by XuetaoLiu-CLS** [comment]
@iainworkman in case you can't find it. the SR570 coordinator is current running from 
`/home/acquaman/AcquamanProjects/SR570Coordinator/acquaman/build`

**Pull request merged**
