### PR TITLE
Pull Request for Issue1361: add IC0/IC1 HV controls to the SXRMB Beamline

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
add Enable IC0/IC1 HV control to the EXAFS scan configuration view

### CODE REVIEW

**Comment by XuetaoLiu-CLS** [comment]
Tested

**Comment by iainworkman** [comment]
Had a look over this and can't see anything wrong myself. Looks good.

**Comment by dretrex** [comment]
This looks good @XuetaoLiu-CLS.  You are now just waiting on testing?

**Comment by XuetaoLiu-CLS** [comment]
@dretrex @davidChevrier asked me to talk with the beamline staff about the security risks of this HV control. Whether there is anything we should take into consideration.

**Comment by XuetaoLiu-CLS** [comment]
Asked BL staff, no risk issue for this. It is good to go now

**Pull request merged**
