### PR TITLE
Pull Request for Issue2389: Investigating QSortFilterProxyModel crashes

### PR DESCRIPTION
**Pull request by helfrij**
Modified `AMMainWindow::expandAllHeadings()` to use `AMMainWindow::expandHeadingIndex(...)` instead of `QTreeView::expandAll()`. This seemed to be the cause of the startup crashes.

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @iainworkman, would you review?

**Comment by iainworkman** [comment]
Interesting that a crash should be caused by calling a method in a standard Qt class. I wonder if it's pointing to some underlying problem in the model?
Otherwise looks good.
Time Estimate: 20 minutes.

**Comment by helfrij** [comment]
Yeah. These are the changes that seem to make the crashes stop--honestly, I just can't say much more than that at this point.

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 3 minutes

**Pull request merged**
