### PR TITLE
Pull Request: general ladder-type control

### PR DESCRIPTION
**Pull request by helfrij**
The existing carbon filter farm controls on BioXAS (#1527) and the proposed diagnostic ladder control (#1689) seem to have some functionality in common:
- are pseudomotors -- they translate feedback from a 'real' motor into new information.
- have enumerated values -- the value can be one of a set of discrete value options.

I've made two classes that handle the enumeration needs for the carbon filter farm controls:
- [x] AMEnumeratedControl
- [x] AMSingleEnumeratedControl

The general enumerated control handles managing a list of the available option indices, matching each index to a string representation, and generating enum and move enum states from these lists. Now inheriting from AMEnumeratedControl:
- [x] BioXASCarbonFilterFarmFilterControl

AMSingleEnumeratedControl inherits from AMEnumeratedControl and additionally manages the relationship between the control and a single subcontrol. This is basically a convenience subclass, as I anticipate most AMEnumeratedControl subclasses will depend on just one subcontrol. Now inheriting from AMSingleEnumeratedControl:
- [x] BioXASCarbonFilterFarmActuatorWindowControl
- [x] BioXASCarbonFilterFarmActuatorFilterControl

There are many more possible applications for these controls on BioXAS, and hopefully they will make implementing the ladder control on SGM easier too.

### CODE REVIEW

**Comment by dretrex** [comment]
Overall, I think it looks good.  Definitely a good start.

As a pedantic detail, I would say that the name could be a bit more general.  To represent the abstraction, maybe something like `AMPseudoMotorEnumeratedControl` or something that showcases that this subclass is meant for enumerated pseudomotors.

Time Estimate: 10 minutes

**Comment by helfrij** [comment]
Quite right--I've renamed the control.

**Comment by helfrij** [comment]
Hey @dretrex. I've done some more work on the controls and some testing with the carbon filter farms on Side and Main. So far, so good. Are you available to take another look at these classes?

**Comment by dretrex** [comment]
I only have one question about the changes.  What is the use case for the duplicate entries?  Can you give an example?  Otherwise, changes seem good.

**Comment by helfrij** [comment]
For the BioXAS carbon filter farm controls, it didn't make sense to have duplicate entries (eg. two '50' filter options) even though there are actually two valid filters with thickness 50. But I didn't want to restrict the general class unnecessarily.

**Comment by dretrex** [comment]
Okay.  Is this good to be merged in or were you wanting to do more work on it?

**Comment by helfrij** [comment]
It's done. Thanks @dretrex.

**Comment by helfrij** [comment]
Time Estimate: 3 days

**Pull request merged**
