### PR TITLE
Pull Request for Issue 1529: In plane trajectory motions of the hexapod

### PR DESCRIPTION
**Pull request by iainworkman**
Added new PVs for trajectory moves, handled their logic in the AMPIC887DriverServer, and added classes to read/write to these PVs in SGM Acquaman.

~~NOTE: With the commissioning tests I've written all of Issue1529 without being able to run or test anything. It'll need significant test before being ready for review.~~

~~NOTE2: This PR also currently contains commits for Issue1423. This will be sorted once #1528 is complete.~~

### CODE REVIEW

**Comment by dretrex** [comment]
Although I've been assigned to this.  Would you like me to hold off on the testing for the time being or give it a first pass pre-testing?

**Comment by iainworkman** [comment]
You can hold off for now. I suspect there will be a bunch of small bug changes in it, and there's no point in you looking over it twice.

**Comment by dretrex** [comment]
Okay sounds good.  Let me know when you want me to go over it.

**Comment by iainworkman** [comment]
@dretrex 
This is now ready for review.

**Comment by dretrex** [comment]
Looks good to me.
Time Estimate: 10 minutes

**Pull request merged**
