### PR TITLE
Pull Request for Issue2033: Add Soller slit controls

### PR DESCRIPTION
**Pull request by helfrij**
- Created new class BioXASSollerSlit. Added instance to BioXASSideBeamline with appropriate motor controls.
- Created new view class BioXASSollerSlitView. Added instance BioXASAppController.

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @XuetaoLiu-CLS, would you have a look?

**Comment by XuetaoLiu-CLS** [comment]
Looks good.

Time Estimates: 5 minutes

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 5 minutes

**Comment by helfrij** [comment]
Hey @dretrex, can this be merged in?

**Comment by dretrex** [comment]
Yes.  I must have just not merged it in since there were no comments.  My bad.

**Pull request merged**
