### PR TITLE
Pull Request for Issue1495: Complete icon package

### PR DESCRIPTION
**Pull request by dleacock**
Added:
* 10, 16, 22, 32px yellow LED on/off icons

Time Estimate: 2

### CODE REVIEW

**Comment by dretrex** [comment]
Is this done @dleacock?  If so I'll merge it in.

**Comment by dretrex** [comment]
Also, is the time estimate what you are assuming it will take for the pull request or in reference to the issue?

**Comment by dleacock** [comment]
Done.  Time estimated: Roughly an hour

**Comment by dleacock** [comment]
Yes, it was. I removed the "2" here and edited the comments in the Issue.

**Comment by dretrex** [comment]
Time estimate: 1 minute

**Pull request merged**
