### PR TITLE
Pull Request for Issue1100: Some exposed controls aren't available to exporter (REIXS)

### PR DESCRIPTION
**Pull request by iainworkman**
Altered REIXSXESScanActionController/REIXSXASScanActionController::initializePositions() ~ Appended ringCurrent, epuPolarization, epuPolarizationAngle, monoGratingTranslation and monoMirrorTranslation to the list of controls which are used to set the scan's initial conditions.

#1100

### CODE REVIEW

**Comment by iainworkman** [comment]
Will need access to running a scan on REIXS to test whether this has resolved the issue.

**Comment by dretrex** [comment]
Can you facilitate that at all @epengr?

**Comment by XuetaoLiu-CLS** [comment]
Looks good to me

**Comment by dretrex** [comment]
Looks good to me too.

**Comment by dretrex** [comment]
Post the results of your tests when you get the chance to do them @iainworkman and we'll merge it in after that.

**Comment by iainworkman** [comment]
Sure, I've spoken to Dave and will be running various tests on REIXS this Monday.

**Comment by epengr** [comment]
Testing done. Works as expected.

**Comment by iainworkman** [comment]
The above comment was me, btw. Dave had logged in - so it posted under his account.

**Pull request merged**
