### PR TITLE
PullRequest for Issue1661: Register SXRMB database informtion

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**

### CODE REVIEW

**Comment by XuetaoLiu-CLS** [comment]
This doesn't work as expected since we are mapping the facility ID with facility description (AMFacility) by using the order they added to the DB instead of the real ID.

**Comment by XuetaoLiu-CLS** [comment]
This should solve the issue now!

**Comment by XuetaoLiu-CLS** [comment]
Need database upgrade for this.

**Comment by dretrex** [comment]
I'm going to merge this in now since the other aspect of this problem is already an issue.  Thanks for looking into this @XuetaoLiu-CLS!

**Comment by davidChevrier** [comment]
Time Estimate: 2 minutes

**Pull request merged**
