### PR TITLE
Pull Request for Issue1899: Adding Zebra checks to BioXASXASScanActionController.

### PR DESCRIPTION
**Pull request by helfrij**

### CODE REVIEW

**Comment by helfrij** [comment]
Hey @XuetaoLiu-CLS, would you mind taking a look at this pull request?

**Comment by XuetaoLiu-CLS** [comment]
Looks good. The function `buildScanControllerImplementation()` is really big though.

Time Estimates: 5 minutes

**Comment by dretrex** [comment]
Also looks good from my end.  @XuetaoLiu-CLS, in general, the `buildScanControllerImplementation()` method is going to be really large because most of the meat of the controller is built there.  Now if you're referring to having smaller helper functions, then that is a different story and probably quite valid since some of the scan controller code can get a little unwieldy at times.

Time Estimate: 5 minutes

**Comment by helfrij** [comment]
Breaking this single method up into smaller function calls is something worth looking into. It may be tricky for BioXAS, as many of the component pieces are interconnected (eg. only do this if I0Detector is non-zero, etc).

**Comment by dretrex** [comment]
You may be able to get away with making some helper methods like the following:

```c++
if (hasI0())
     addI0Helper();
```

rather than having something like:

```c++
addI0();
addI1();
addI2();
```

Some food for thought.

**Pull request merged**
