### PR TITLE
PullRequest for Issue1786: disable sumSelector to change axisSum_ for 2DSumming, 3D/4DBinning analysis block

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
#1786
- some code refactor for AM2DSummingAB
- disable the combobox of sumSelector to change the axisSum_ of 2DSummingAB, 3DBinningAB and 4DBiningAB

### CODE REVIEW

**Comment by XuetaoLiu-CLS** [comment]
@dretrex I didn't use QLabel for the sum selector as you suggested. I still keep the combox, but I disabled it. Maybe in the future we might still want to use the combox?

**Comment by dretrex** [comment]
That's fair.

**Comment by dretrex** [comment]
Couple comments:

- With the refactors, does the 2D summing block still work appropriately after your refactor of `setInputSource()`?
- Did AM3DBinningAB and AM4DBinningAB not need to be initialized to use the last rank of the input source?
- Was the second version of `canAnalyze()` not used?  I just want to make sure that the refactors you did do not cause further issues.

Time Estimate: 10 minutes

**Comment by XuetaoLiu-CLS** [comment]
@dretrex 
1) yes, `setInputDataSourcesImplementation` still works after the refactor. Basically there are a lot of redundant codes in `setInputDataSourcesImplementation()` and `updateInputSource()`. and the `updateInputSource()` was called by the `setInputDataSourcesImplementation`.
2) AM2DBinningAB already sets sumAxis_ to 2 and AM3DBinningAB already set sumAxis to 3
3) the second version of `canAnalyze()` is not used since what it did is to update the `canAnalyze_` flag, which is updated again in the function `updateInputSource()`

**Comment by dretrex** [comment]
Okay.

**Pull request merged**
