### PR TITLE
Pull Request for Issue 1906: Remove Detector Mode Check from Scan Action Assemblers

### PR DESCRIPTION
**Pull request by iainworkman**
Removed the check to ensure that the read mode was request read when adding detectors to the scan action assemblers, as it was interfering with XRF detectors.

### CODE REVIEW

**Comment by iainworkman** [comment]
Hey @XuetaoLiu-CLS  Would you mind having a look at this pull request. It basically undos the code added by #1890 , so it should be straight forward.

**Comment by XuetaoLiu-CLS** [comment]
Looks good. But why do we want to redo the changes?

Time Estimates: 5 minutes

**Comment by dretrex** [comment]
Looks good.

Time Estimate: 1 minute

**Comment by dretrex** [comment]
@XuetaoLiu-CLS, it's because the read mode is not actually used by the scaler or AMXRFDetector.  It was causing issues where the scans could not dynamically change the time at the end of regions and during EXAFS scans because the Scaler and XRF detectors aren't set that way.  In fact, you may want to update the SXRMB deployment because they will probably be effected by this.

**Pull request merged**
