### PR TITLE
PullRequest for Issue1755: combine fix for some issues of SXRMB

### PR DESCRIPTION
**Pull request by XuetaoLiu-CLS**
https://github.com/acquaman/acquaman/issues/1755

Changes for:
- [x] MotorGroup view using scientific format to display the values, which is not user-friendly
- [x] Acquaman crashed when doing "view" --> "See Ambiant Sample Stage Motors"
- [x] ROI counts won't update for Bruker detector 
- [x] cannot beam on after injection
- [x] Slit View range incorrect. Should be up to 16mm (fully open)
- [x] EXAFS region scan: there is glitch data for the scan data, it happens when doing the K-space scanning.
  fixes: changed the tolerance of dwellTime_ pv control for the scaler
- [x] add auto normalization for 4Element Votex

### CODE REVIEW

**Comment by dretrex** [comment]
Time Estimate: 15 minutes

**Comment by dretrex** [comment]
Why was this closed?

**Comment by XuetaoLiu-CLS** [comment]
It was merged to master.

**Comment by dretrex** [comment]
Oh, it was merged manually!  I see now.

**Comment by XuetaoLiu-CLS** [comment]
Yes. I don’t know how it happened though ☹.

X.L.

**Pull request closed without merging**
